
### recuperar todas las peliculas
GET http://localhost:3000/movies


### recuperar una pelicula por id
GET http://localhost:3000/movies/5ad1a235-0d9c-410a-b32b-220d91689a08

### recuperar peliculas por un genero

GET http://localhost:3000/movies?genre=crime 

### crear una pelicula con POST
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "http://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ],
  "rate": 9

}

### borrar una pelicula

DELETE http://localhost:3000/movies/392380ab-cb43-4441-81ac-8427b0b9d0ca

### actualizar una pelicula

PATCH http://localhost:3000/movies/392380ab-cb43-4441-81ac-8427b0b9d0ca
Content-Type: application/json

{
  "title": "The Momo"
}